[[SassC]]
arch = "aarch64"
git-tree-sha1 = "a36267fb96786004779ed18032ab122492f66940"
os = "macos"

    [[SassC.download]]
    sha256 = "2920e83451911c8b1eba526b29a9809fbfa995604bbac79acc2b515aaf8f781d"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.aarch64-apple-darwin.tar.gz"
[[SassC]]
arch = "aarch64"
git-tree-sha1 = "db143de0e61f4ba958f3adb42205d723de585085"
libc = "glibc"
os = "linux"

    [[SassC.download]]
    sha256 = "2db125111706123487defd2e0abe3cd253c33357fa90e5d352df1114f06cf631"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.aarch64-linux-gnu.tar.gz"
[[SassC]]
arch = "aarch64"
git-tree-sha1 = "f0db3f2375d5c7739418e89b8f93199fac82fb33"
libc = "musl"
os = "linux"

    [[SassC.download]]
    sha256 = "09753ab014fa814293440aec15ef974c308f12760326e61b8bd39005efc35e1c"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.aarch64-linux-musl.tar.gz"
[[SassC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a201f26883760e5cfab9be5ea8cd3868978a0d87"
libc = "glibc"
os = "linux"

    [[SassC.download]]
    sha256 = "c357346bba2a63d3914d8d531aec8f94a111371b743277610d78e68eea023aab"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.armv6l-linux-gnueabihf.tar.gz"
[[SassC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "22222a147865d06d3b6084f6fb7212134ea45a7e"
libc = "musl"
os = "linux"

    [[SassC.download]]
    sha256 = "7dcf7f42db15b45d1ae0f17982dd934fa5cbacb40183985097cb613dec7a4e8b"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.armv6l-linux-musleabihf.tar.gz"
[[SassC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31b4132268fd9d53fc56109ac22cc1eb5bd0a208"
libc = "glibc"
os = "linux"

    [[SassC.download]]
    sha256 = "c7a6d49c42a958d09a3b14ccec159f14de58c4f716f3284aaebb529761f70bfc"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.armv7l-linux-gnueabihf.tar.gz"
[[SassC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cdf482dc36d60e810b5f58ccf226746602151863"
libc = "musl"
os = "linux"

    [[SassC.download]]
    sha256 = "f67727bba48ddd89df7ea97d03652c33458e796ec0be588858be949f25eacc19"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.armv7l-linux-musleabihf.tar.gz"
[[SassC]]
arch = "i686"
git-tree-sha1 = "d6d1196480428208fad515be30e2d16895407402"
libc = "glibc"
os = "linux"

    [[SassC.download]]
    sha256 = "d60fe7b3bbcd880a18377af6560dd3d0d9775ca540ce0082d3f612f3b7a35bc6"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.i686-linux-gnu.tar.gz"
[[SassC]]
arch = "i686"
git-tree-sha1 = "2e675d2f78bb097de00272d0f943bbf5317cd1e3"
libc = "musl"
os = "linux"

    [[SassC.download]]
    sha256 = "82e10909c1bbcf51b07550754f15ac98653c0d5db66de2f8d7947b9a1a6440ef"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.i686-linux-musl.tar.gz"
[[SassC]]
arch = "i686"
git-tree-sha1 = "8c14c1c9590023cf18f5fcbf0497acf4b89e058d"
os = "windows"

    [[SassC.download]]
    sha256 = "40dd158a195238adfd30328bafcbf53b33979edddafddab861f549651fd50023"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.i686-w64-mingw32.tar.gz"
[[SassC]]
arch = "powerpc64le"
git-tree-sha1 = "9ecbd034dad3a88ee936f7f424ed95562622cee0"
libc = "glibc"
os = "linux"

    [[SassC.download]]
    sha256 = "4d2df6398a95f4324d296905d08f63e8a22ca483e42551d6e64bcb6cfe59ba29"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.powerpc64le-linux-gnu.tar.gz"
[[SassC]]
arch = "x86_64"
git-tree-sha1 = "611a5d4afb9d657a4a2a60c6282a29f2f1687d3c"
os = "macos"

    [[SassC.download]]
    sha256 = "f2ffc88a6e6b81c3f2197223834e4b42ca45153e79c8e0f4dd48de459447a4df"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.x86_64-apple-darwin.tar.gz"
[[SassC]]
arch = "x86_64"
git-tree-sha1 = "c989f64557a11a85bb357f802329d70ba0785379"
libc = "glibc"
os = "linux"

    [[SassC.download]]
    sha256 = "75da361220514ea122411f1d3bfb40d5dabfc26a580291512771c43b9e4448bd"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.x86_64-linux-gnu.tar.gz"
[[SassC]]
arch = "x86_64"
git-tree-sha1 = "f8b7b81397434cad19c6b1f5343725e864093c9a"
libc = "musl"
os = "linux"

    [[SassC.download]]
    sha256 = "593a1c5635f2d375676e6fe809e59d0dc6a5c53764b347f4c1107f1c24914ab0"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.x86_64-linux-musl.tar.gz"
[[SassC]]
arch = "x86_64"
git-tree-sha1 = "672f01fb682c34eaaa966851359def1a485fb323"
os = "freebsd"

    [[SassC.download]]
    sha256 = "5fcbb5289203643e5c8c8a1078ea8ad2d1ff526693c2f0ddd67ece80e405fb69"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.x86_64-unknown-freebsd.tar.gz"
[[SassC]]
arch = "x86_64"
git-tree-sha1 = "20023ca24b54d474c8035b9a4b25ebbf2fa8ac45"
os = "windows"

    [[SassC.download]]
    sha256 = "7ba0f235715c9e45703bcf9b80e34e71905a056c8f427debfa8ec8572a9c1c03"
    url = "https://github.com/JuliaBinaryWrappers/SassC_jll.jl/releases/download/SassC-v3.6.2+0/SassC.v3.6.2.x86_64-w64-mingw32.tar.gz"
